### ISSUE TITLE
On launch: `Can't create table `commentron`.`moderator` (errno: 121 "Duplicate key on write or update") handling 003_blocked.sql`

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/commentron#113]
Tried to run commentron locally, but getting this error when running: `./commentron serve`

MySQL instance is MariaDB on Manjaro.
```
PANI[0000] Error 1005: Can't create table `commentron`.`moderator` (errno: 121 "Duplicate key on write or update") handling 003_blocked.sql
panic: (*logrus.Entry) 0xc00013a150

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc00013a0e0, 0x0, {0xc0002dc100, 0x80})
        /home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x43e
github.com/sirupsen/logrus.(*Entry).Log(0xc00013a0e0, 0x0, {0xc000157cf8?, 0xc00032e2d0?, 0x1326b20?})
        /home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Logger).Log(0xc00013a000, 0x0, {0xc000157cf8, 0x1, 0x1})
        /home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:198 +0x65
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:247
github.com/sirupsen/logrus.Panic(...)
        /home/user/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/exported.go:129
github.com/lbryio/commentron/config.InitializeConfiguration(0xc0003225b0)
        /home/user/git/commentron/config/config.go:34 +0xeb
github.com/lbryio/commentron/cmd.glob..func2(0x1368620?, {0x13abe08?, 0x0?, 0x0?})
        /home/user/git/commentron/cmd/serve.go:41 +0xf5
github.com/spf13/cobra.(*Command).execute(0x1368620, {0x13abe08, 0x0, 0x0})
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1368380)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/lbryio/commentron/cmd.Execute()
        /home/user/git/commentron/cmd/root.go:32 +0x25
main.main()
        /home/user/git/commentron/main.go:10 +0x17
```

**Comment by kodxana** [comment]
MariaDB don't work well with commentron trust me.
